### ISSUE TITLE
Error: Please check your hook name: woocommerce_shop_loop_item_title

### ISSUE THREAD

**Issue by oquirozm** [hambos22/sage-woo#11]
Hi again,

I'm getting the following error only when using the woocommerce_shop_loop_item in the 'add' settings at the sage-woo.yml: 
Warning: Please check your hook name: woocommerce_shop_loop_item_title in /srv/www/glaudicollection.com/current/web/app/themes/sage-woo/app/SageWoo/Modules/Actions.php on line 121

It's really weird. I'm using the same hook to remove an action and it works. It will only throw that error when trying to add an action.

**Comment by hambos22** [comment]
Thanks for this. I just realised that the way which I used the `has_action` was wrong. I believe that is developer's responsibility to have action names right. Please see https://github.com/hambos22/sage-woo/commit/17ec44e501edbce5b052b3a14d0c47eeaee7c59f

**Comment by oquirozm** [comment]
great! I think is the best way to go, too. Thanks for fixing it so quickly.
