### ISSUE TITLE
controller for archive-product.blade.php

### ISSUE THREAD

**Issue by oquirozm** [hambos22/sage-woo#12]
I'm becoming a regular on this repo 😄 
In the README you say

> 'Woocommerce support out of the box with working Controller (for single-product, archive-product)'

but further below you write

> Controller only works on content-product and content-single-product because they got included via Blade

So, does it work with archive-product? I ask because I'm having trouble making that controller work. Is it an error on my side or it is just that it isn't supported?

**Comment by hambos22** [comment]
Hi,

Controller works only on files which included via blade. On `archive-product` it works as expected. Maybe you need to name your controller `ArchiveProduct` or something similar. Put a `@debug` on `archive-product.blade.php` and see the hierarchy

**Comment by oquirozm** [comment]
I've created controllers with templates and haven't got any problem. Can you tell me if I'm creating the controller for archive-product correctly?

Currently I:

- Create the archive-product.php inside the app/controllers directory.
- place this code inside it:
   ` <?php
`

**Comment by hambos22** [comment]
Change it to `archive.php` and `Archive` class name and try again. Shop/tax pages have the `archive` as a body class

**Comment by oquirozm** [comment]
@hambos22 it worked out! Thanks.
