### ISSUE TITLE
Fatal error: Uncaught ReflectionException: Class App\Controllers\App does not exist in

### ISSUE THREAD

**Issue by alexanderdejong** [hambos22/sage-woo#16]
Hi @hambos22, thank you for this cool fork of Sage! I really like some of the ideas you got going in this forked version. I've been developing locally and tried to push my work to my staging server but ran into some issues regarding SoberWP and the classes in the project. Perhaps you can help me troubleshoot it. 

## Bug report fatal error with Class App\Controllers\App

Here is the error I'm getting: 

`Fatal error: Uncaught ReflectionException: Class App\Controllers\App does not exist in /home/mycoolapplocation/webapps/app-namemyapp/web/app/themes/foldername/vendor/soberwp/controller/src/Loader.php:74 Stack trace: #0 /home/mycoolapplocation/webapps/app-namemyapp/web/app/themes/foldername/vendor/soberwp/controller/src/Loader.php(74): ReflectionClass->__construct('App\\Controllers...') #1 /home/mycoolapplocation/webapps/app-namemyapp/web/app/themes/foldername/vendor/soberwp/controller/src/Loader.php(35): Sober\Controller\Loader->setPath() #2 /home/mycoolapplocation/webapps/app-namemyapp/web/app/themes/foldername/vendor/soberwp/controller/controller.php(22): Sober\Controller\Loader->__construct(Object(Brain\Hierarchy\Hierarchy)) #3 /home/mycoolapplocation/webapps/app-namemyapp/web/wp/wp-includes/class-wp-hook.php(286): Sober\Controller\loader('') #4 /home/mycoolapplocation/webapps/app-namemyapp/web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 /home/mycoolapplocation/webapps/app-namemyapp/web/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /home/normajea in /home/mycoolapplocation/webapps/app-namemyapp/web/app/themes/foldername/vendor/soberwp/controller/src/Loader.php on line 74`

## Bug report

**Where did the bug happen? Development or remote servers?**
(Remote) Staging Server

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

I tried the solution proposed here with no luck.
[https://github.com/soberwp/controller/issues/55](url)

**Other relevant information:**

I tried installing a clean version of sage-woo but this does not work on my staging server. Locally the project works but as soon as I try to start the project on my server it fails with the error above.

**Comment by hambos22** [comment]
Hi,
Change `app.php` to `App.php` and try again!

**Comment by alexanderdejong** [comment]
Cheers! I capitalized both the filename and the Controllers folder and now it works.
