### ISSUE TITLE
How to create blade templates for specific category slugs

### ISSUE THREAD

**Issue by stevebasford** [hambos22/sage-woo#17]
Is it possible to use blade templates for category slugs? For example:
`taxonomy-product_cat-hearing-protection.blade.php`
Do I need to add this to the router some how?

**Comment by hambos22** [comment]
Sure. For adding it to the router, check its body classes. For a name like this, it should be `taxonomyProduct_catHearingProtection`

**Comment by stevebasford** [comment]
Apologies, could you elaborate on 'check its body classes'. So after I've created a file in the name as specified above, what's the next step to getting the category page to use that template?

**Comment by hambos22** [comment]
Check body classes of the page you want the controller to work. Some of them might be like `single-product-data`. Look those with the `data` suffix. Then convert those to camelCase, like `SingleProduct`, without the data suffix

**Comment by stevebasford** [comment]
Okay sorry if I'm being dumb but here goes:

The body class of the page is `taxonomy-product_cat-hearing-protection-data`.
I've tried creating `taxonomyProduct_catHearingProtection.blade.php` and `taxonomy-product_cat-hearing-protection.blade.php` in both the views directory and the woocommerce directory but neither of them are being used on the page?

**Comment by stevebasford** [comment]
Fyi I couldn't get this working with the above method so just set it up like thishttps://stackoverflow.com/questions/50612737/changing-wordpress-template-for-specific-product-category-page/50616815#50616815

**Comment by hambos22** [comment]
Sorry for the totally late answer, I didn't see the notification. Yeah this seems legit. I remembered that I wanted to do the same once, and I followed the same approach (I was kind of lazy to create a new template only for this)
