### ISSUE TITLE
Using photoswipe

### ISSUE THREAD

**Issue by TMcLoone** [hambos22/sage-woo#6]
Hey there, thank you so much for creating this. It really has saved me a lot of time. This is my first time working with woocommerce, I kind of have everything figured out but I was wondering if you knew a way to get photoswipe ( http://photoswipe.com/ ) working with the product images? I see that woocommerce has photoswipe.php in their single-product templates but I don't see where/how it's getting used. Any idea?

**Comment by hambos22** [comment]
Hello. Please use this section only for issues and not general questions/support.

You can find what you want [here](https://woocommerce.wordpress.com/2017/02/28/adding-support-for-woocommerce-2-7s-new-gallery-feature-to-your-theme/) 😎. Drop those lines on `after_setup_them` hook and you're ok

**Comment by TMcLoone** [comment]
Oh wow sorry about that, I thought it was something you'd removed.
