### ISSUE TITLE
Variation data under product name in cart

### ISSUE THREAD

**Issue by stevebasford** [hambos22/sage-woo#7]
Not sure this relates to sage-woo as such but how do I get product variation data to show under the product title link in the cart? Is this not default behaviour?

**Comment by hambos22** [comment]
I think the variation data is under the select box. Just change the order of the hooks if any. I usually hide the variation data and with the JS event `show_variation` I catch the `price_html` and replace the **price** under the title

**Comment by hambos22** [comment]
Closing since no feedback given

**Comment by stevebasford** [comment]
Sorry for the slow reply, I'll look into what you've said. Thank you.

**Comment by stevebasford** [comment]
It seems to show up fine on another site I've made with your template so it must have been something I unintentionally did to not get it to show up.
