### ISSUE TITLE
Too many HTTP-Redirects

### ISSUE THREAD

**Issue by ouun** [hambos22/sage-woo#8]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Page load time is >15s with SageWoo while with original sage <1.5s. The reason is that `dist/styles/main.css` and `dist/scripts/main.js` are redirected to `dist/styles/domain.test` while `domain.test`is the domain of the page.

**What is the expected or desired behavior?**

There is no redirect. Changing the theme to regular sage, it just works as expected. 

---

## Bug report

**Please provide steps to reproduce, including full log output:**

I tried to find the source for the redirects but wasn't able to find it. 

**Please describe your local environment:**

WordPress version: 4.9.5

OS: MacOS

NPM/Node version: X

**Where did the bug happen? Development or remote servers?**

Development Server

**Comment by hambos22** [comment]
Hi

I can't reproduce the issue. My loading time is ~1s. I remember that the trailing slash on the `devUrl` and `publicPath` at `config.json` caused issues and redirections and I removed it. Also it's been a while since I removed webpack dashboard, do you have it on? Could you try again with the new setup?

Thanks

**Comment by ouun** [comment]
Thank you very much for the fast response @hambos22.
Just rechecked the settings in `config.json` and it seems to be all fine as I have not set any trailing slash: 

```
"publicPath": "/app/themes/test-theme",
  "devUrl": "http://shop.example.test",
  "proxyUrl": "http://localhost:3000",
  "cacheBusting": "[name]_[hash:8]",
```

I also just set up a complete new theme to test this behavior. The outcome is that as long as I'm not setting the correct "devURL" but keep the default "http://woo.test" at least the sites load very fast after `yarn run build:production`. But as soon as I set the correct domain ("http://shop.example.test") the page loads but is as slow as described and has the redirects. This is the same for built assets as well as `yarn run start`.

Maybe you have another idea? I really appreciate you help!

**Comment by ouun** [comment]
Hi @hambos22,

thank you for your replies and sorry for my delay in answering. I took some vacation for the past week.
Please find attached the zip'ed theme file.

[anani.zip](https://github.com/hambos22/sage-woo/files/1931543/anani.zip)

Thank you again an best regards,

Philipp

**Comment by hambos22** [comment]
Haha never mind! I'm glad you solved the issue. (between us I do this mistake all the time accidentally)
